import { openrouter } from "@lib/openrouter/client";
import { generateObject } from "ai";
import { z } from "zod";

export async function generateChatNameWithAi(userPrompt: string) {
  const prompt = `
Generate a short, creative, and relevant chat title based on the message content below. The title should describe the topic of the conversation, not answer it. Use the same language as the message. Limit to 50 characters.
Only return the name — no explanations or extra text.
Do not include quotation marks around the name.

Examples:
Message: "Oi, qual o seu nome?"
Title: "Primeiro Contato"

Message: "Preciso de ajuda com JavaScript."
Title: "Debugando com JS"

Message: "Como funciona o sistema solar?"
Title: "Explorando o Espaço"

Message: "${userPrompt}"
Title: 
`;

  const aiResponse = await generateObject({
    model: openrouter("deepseek/deepseek-chat-v3-0324:free"),
    prompt,
    maxTokens: 30,
    schema: z.object({
      title: z.string({ description: "Title generated by AI" }),
    }),
  });

  const chatName = aiResponse.object.title.replace("\n", "").trim();

  return chatName;
}
